# Change these first
owner: BoltDevelopment # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Tynker
    url: https://tynker.scriptedev.repl.co/
    assignees:
      - CodrDev
  - name: FrozenYogurt
    url: https://FrozenYogurt.scriptedev.repl.co/
    assignees:
      - CodrDev
  - name: CDN
    url: https://cdn.boltdev.tk/
    assignees:
      - CodrDev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  theme: dark
  cname: status.boltdev.tk
  # baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/81486521?s=50&v=4
  favicon: https://avatars.githubusercontent.com/u/81486521?s=50&v=4
  faviconSvg: https://avatars.githubusercontent.com/u/81486521?s=50&v=4
  name: Bolt Development Status
  introTitle: "Hey, is one of our services / bots not working?"
  introMessage: This page shows the status of our bots & services, as well as updates on the issues.
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://dsc.gg/boltdev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
